// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe_JpUyKEbuVGQcIPokpCyB2BFMOIuBm8',
    appId: '1:224724597230:web:58758da93fb9be2776b6ff',
    messagingSenderId: '224724597230',
    projectId: 'bitsonwheelsv1',
    authDomain: 'bitsonwheelsv1.firebaseapp.com',
    storageBucket: 'bitsonwheelsv1.firebasestorage.app',
    measurementId: 'G-5W4LZ5LXJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4rXcxx2JBpJDGyR5tT0zk8ZAK3irNXM',
    appId: '1:224724597230:android:7ef3b746eb5aef3f76b6ff',
    messagingSenderId: '224724597230',
    projectId: 'bitsonwheelsv1',
    storageBucket: 'bitsonwheelsv1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyJZWuMtYYHeiblRGZNtV4WsoEpBifGI',
    appId: '1:224724597230:ios:3aa03f09f2b6e97b76b6ff',
    messagingSenderId: '224724597230',
    projectId: 'bitsonwheelsv1',
    storageBucket: 'bitsonwheelsv1.firebasestorage.app',
    iosBundleId: 'com.example.bitsonwheelsv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyJZWuMtYYHeiblRGZNtV4WsoEpBifGI',
    appId: '1:224724597230:ios:3aa03f09f2b6e97b76b6ff',
    messagingSenderId: '224724597230',
    projectId: 'bitsonwheelsv1',
    storageBucket: 'bitsonwheelsv1.firebasestorage.app',
    iosBundleId: 'com.example.bitsonwheelsv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe_JpUyKEbuVGQcIPokpCyB2BFMOIuBm8',
    appId: '1:224724597230:web:d071dc30da3e82e576b6ff',
    messagingSenderId: '224724597230',
    projectId: 'bitsonwheelsv1',
    authDomain: 'bitsonwheelsv1.firebaseapp.com',
    storageBucket: 'bitsonwheelsv1.firebasestorage.app',
    measurementId: 'G-M51X3KCX4E',
  );
}
